# California Season Prediction

## Imports and Functions

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
from sklearn.gaussian_process import GaussianProcessRegressor


from sklearn.svm import SVR
import os
import numpy as np
from xgboost import XGBRegressor
import sys

In [2]:
# Add the folder to the Python path

os.chdir("../../")
# change working directory to project's root path
print(os.getcwd())

FIRST_YEAR= 1972

c:\Users\marti\Desktop\data\hw_extra

In [3]:
folder_path = os.path.abspath("functions/") #INPUT_PATH)#'path_to_your_folder')  # Replace with the actual folder path
sys.path.insert(0, folder_path)

from Predictions import (
    PredictionExperiment,
    PredictionModel
)

In [4]:
data = {i: pd.read_csv(f"data/features/california/from{FIRST_YEAR}/HWs_cali_features_biseason_{i}.csv") for i in range(1,13)}

##   DJ-JF-FM

In [5]:
kernel = RBF(length_scale=1.0) + WhiteKernel(noise_level=1)
regressors = [LinearRegression(),RandomForestRegressor(random_state=42, n_estimators=5), RandomForestRegressor(random_state=42, n_estimators=10), SVR(kernel='rbf'),
                XGBRegressor(random_state=42, n_estimators=10, learning_rate=0.1),XGBRegressor(random_state=42, n_estimators=15, learning_rate=0.1), GaussianProcessRegressor(kernel=kernel, random_state=42, n_restarts_optimizer=10)]
name_regressors = ["Linear", "RF5", "RF10", "SVR-rbf", "XGB10", "XGB15", "GPR"]

In [6]:
data_summer = {i: data[i] for i in [1,2,3]}
indices_of_interest = ["HWN", "HWF", "HWD", "HWM", "HWA"]

In [7]:
experiment_1 = PredictionExperiment(data_summer, indices_of_interest, regressors, name_regressors, 5)

In [8]:
experiment_1.execute_experiment()

In [9]:
experiment_1.plot_metrics("r2", "prediction", thresh=0.5)

In [10]:
experiment_1.plot_metrics("r2", "training", thresh=0.9)

In [11]:
experiment_1.plot_metrics("mape", "prediction", thresh=0.3, above=False)

In [12]:
experiment_1.plot_metrics("cv_r2")

## Winter

In [13]:
kernel = RBF(length_scale=1.0) + WhiteKernel(noise_level=1)
regressors = [LinearRegression(),RandomForestRegressor(random_state=42, n_estimators=5), RandomForestRegressor(random_state=42, n_estimators=10), SVR(kernel='rbf'),
                XGBRegressor(random_state=42, n_estimators=10, learning_rate=0.1),XGBRegressor(random_state=42, n_estimators=15, learning_rate=0.1), GaussianProcessRegressor(kernel=kernel, random_state=42, n_restarts_optimizer=10)]
name_regressors = ["Linear", "RF5", "RF10", "SVR-rbf", "XGB10", "XGB15", "GPR"]

In [14]:
data_summer = {i: data[i] for i in [7,8,9]}
indices_of_interest = ["HWN", "HWF", "HWD", "HWM", "HWA"]

In [15]:
experiment_1 = PredictionExperiment(data_summer, indices_of_interest, regressors, name_regressors, 5)

In [16]:
experiment_1.execute_experiment()

In [17]:
experiment_1.plot_metrics("r2", "prediction", thresh=0.5)

In [18]:
experiment_1.plot_metrics("r2", "training", thresh=0.9)

In [19]:
experiment_1.plot_metrics("mape", "prediction", thresh=0.3, above=False)

In [20]:
experiment_1.plot_metrics("cv_r2")